FROM debian:stable

# kafka bootstrap.servers that tests will use
ARG bootstrap_servers

WORKDIR /root/quicklisp/local-projects/cl-rdkafka/

COPY cl-rdkafka.asd version.lisp ./
COPY src src
COPY test test

RUN apt-get update && apt-get install -y --no-install-recommends \
    sbcl cl-quicklisp gcc libc6-dev librdkafka-dev libffi-dev kafkacat \
    && sbcl --noinform --end-runtime-options \
            --no-sysinit --no-userinit \
            --load $(find / -name 'quicklisp.lisp' -type f) \
            --non-interactive \
            --eval '(quicklisp-quickstart:install)' \
            --eval '(ql:quickload :cffi)' \
            --eval '(ql:quickload :cl-rdkafka/test)' \
            --eval "(sb-ext:save-lisp-and-die \
                      \"test-image\" \
                      :toplevel (lambda () \
                                  (sleep 5) \
                                  (let ((test:*bootstrap-servers* \"$bootstrap_servers\")) \
                                    (asdf:operate :test-op :cl-rdkafka))))" \
            --end-toplevel-options \
    && mkdir /app \
    && mv ./test-image /app/test-image

CMD ["sbcl", "--noinform", "--core", "/app/test-image"]
