# TODO unit tests started failing with debian:stable for some reason,
# so switched to debian:stretch. Need to figure out root cause and
# come up with proper fix, though.
FROM debian:stretch

WORKDIR /root/quicklisp/local-projects/cl-rdkafka/

COPY cl-rdkafka.asd version.lisp ./
COPY src src
COPY test test

RUN apt-get update && apt-get install -y --no-install-recommends \
    sbcl cl-quicklisp gcc libc6-dev librdkafka-dev libffi-dev kafkacat \
    && sbcl --noinform --end-runtime-options \
            --no-sysinit --no-userinit \
            --load $(find / -name 'quicklisp.lisp' -type f) \
            --non-interactive \
            --eval '(quicklisp-quickstart:install)' \
            --eval '(ql:quickload :cffi)' \
            --eval '(ql:quickload :cl-rdkafka/test)' \
            --eval '(sb-ext:save-lisp-and-die \
                      "test-image" \
                      :toplevel \
                        (function cl-rdkafka/test:run-tests-for-shell))' \
            --end-toplevel-options \
    && mkdir /app \
    && mv ./test-image /app/test-image

CMD ["./test/run-tests.bash"]
