FROM debian:stable

WORKDIR /root/quicklisp/local-projects/cl-rdkafka/

COPY cl-rdkafka.asd .
COPY src src
COPY test test

RUN apt-get update && apt-get install -y --no-install-recommends \
    sbcl cl-quicklisp gcc libc6-dev librdkafka-dev libffi-dev kafkacat \
    && sbcl --noinform --end-runtime-options \
            --no-sysinit --no-userinit \
    	    --load $(find / -name 'quicklisp.lisp' -type f) \
    	    --non-interactive \
    	    --eval '(quicklisp-quickstart:install)' \
    	    --eval '(ql:quickload :cffi)' \
    	    --eval '(ql:quickload :cl-rdkafka/test)' \
    	    --eval '(sb-ext:save-lisp-and-die \
                      "test-image" \
                      :toplevel \
                        (function cl-rdkafka/test:run-tests-for-shell))' \
            --end-toplevel-options \
    && mkdir /app \
    && mv ./test-image /app/test-image

CMD ["./test/run-tests.bash"]
